export const faqs = [
  {
    question: "WHAT IS THE TOTAL SUPPLY OF SHARKS?",
    answer: "THERE ARE A TOTAL OF 10,000 NFTS AVAILABLE TO BUY ON OPENSEA.",
  },
  {
    question: "WHAT IS THE PRICE FOR ONE WICKED SHARK NFT?",
    answer: "ALL BIDS WORTH 0.01 ETH WILL BE ACCEPTED",
  },
  {
    question: "WHAT DAY DOES WICKED SHARK CLUB LAUNCH?",
    answer: "THE COLLECTION HAS ALREADY LAUNCHED, CHECK IT OUT ON OPEANSEA",
  },
  {
    question: "IS THERE A WHITELIST SECTION FOR THE COLLECTION?",
    answer:
      "SURE, BEING WHITELISTED YOU'LL GET A SHARK AT A LOWER PRICE, CHECK OUT THE OTHER BENEFITS ON OUR DISCORD SERVER",
  },
];
